version: "3.9"
services:
  web:
    build: ./infra/flask
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
    ports:
      - "5000:5000"
    volumes:
      - ./src:/code